name: Check Copyright Violations

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  check_violation:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 scikit-learn validators markdownify

      - name: Run comparison script
        id: compare
        run: |
          python compare_posts.py
          if [ $? -ne 0 ]; then
            echo "Comparison script failed" > error_message.txt
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Set error message
        if: failure()
        run: |
          echo "ERROR_MESSAGE=$(cat error_message.txt)" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Close Issue
        if: failure()
        run: |
          gh issue close ${{ env.ISSUE_NUMBER }} --comment "Closing reason:\n${{ env.ERROR_MESSAGE }}" -r "not_planned"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Echo result
        if: success() && env.VIOLATION_DETECTED == 'true'
        run: |
          echo "Violation Detected: ${{ env.VIOLATION_DETECTED }}"
          echo "Similarity: ${{ env.SIMILARITY }}"
          echo "Violator URL: ${{ env.VIOLATOR_URL }}"
        env:
          VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED }}
          SIMILARITY: ${{ env.SIMILARITY }}
          VIOLATOR_URL: ${{ env.VIOLATOR_URL }}

      - name: Run Updator
        if: success() && env.VIOLATION_DETECTED == 'true'
        run: |
          echo "Violation detected. Updating README..."
          python update_readme.py
          if [ $? -ne 0 ]; then
            echo "::error::Failed to update README"
            exit 1
          fi
        env:
          VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED }}
          SIMILARITY: ${{ env.SIMILARITY }}
          VIOLATOR_URL: ${{ env.VIOLATOR_URL }}

      - name: Commit README
        if: success() && env.VIOLATION_DETECTED == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED }}
