name: Check Copyright Violations

on:
  issues:
    types: [opened, edited]

jobs:
  check_violation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 scikit-learn validators

      - name: Run comparison script
        run: python compare_posts.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Upload violation artifact
        if: success() && files.exists('violation_detected')
        uses: actions/upload-artifact@v2
        with:
          name: violation-artifact
          path: violation_detected

  update_readme:
    runs-on: ubuntu-latest
    needs: check_violation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download violation artifact
        uses: actions/download-artifact@v2
        with:
          name: violation-artifact
          path: .

      - name: Update README
        run: |
          echo "Violation detected. Updating README..."
          python update_readme.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Add new copyright violator channel"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
