name: Check Copyright Violations

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  check_violation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 scikit-learn validators markdownify

      - name: Run comparison script
        id: compare
        run: |
          python compare_posts.py
          if [ $? -ne 0 ]; then
            echo "::error::Comparison script failed"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
      # - name: Process comparison results
      #   id: process_results
      #   run: |
      #     if [ -f violation_result.txt ]; then
      #       echo "VIOLATION_DETECTED=$(grep VIOLATION_DETECTED violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
      #       echo "SIMILARITY=$(grep SIMILARITY violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
      #       echo "VIOLATOR_URL=$(grep VIOLATOR_URL violation_result.txt | cut -d'=' -f2)" >> $GITHUB_ENV
      #       echo "Results processed successfully"
      #     else
      #       echo "::error::violation_result.txt not found"
      #       exit 1
      #     fi

      - name: Echo result
        run: |
          echo "Violation Detected: ${{ env.VIOLATION_DETECTED }}"
          echo "Similarity: ${{ env.SIMILARITY }}"
          echo "Violator URL: ${{ env.VIOLATOR_URL }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
          SIMILARITY: ${{ env.SIMILARITY}}
          VIOLATOR_URL: ${{ env.VIOLATOR_URL}}
      - name : Run Updator
        if: env.VIOLATION_DETECTED == 'true'
        run: |
          echo "Violation detected. Updating README..."
          python update_readme.py
          if [ $? -ne 0 ]; then
            echo "::error::Failed to update README"
            exit 1
          fi
        env:
            VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
            SIMILARITY: ${{ env.SIMILARITY}}
            VIOLATOR_URL: ${{ env.VIOLATOR_URL}}
      - name: commit README
        if: env.VIOLATION_DETECTED == 'true'

        uses: EndBug/add-and-commit@v9
        with:
            add: README.md
        env:
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VIOLATION_DETECTED: ${{ env.VIOLATION_DETECTED}}
            GITHUB_TOKEN: ${{secrets.PAT}}
